### ISSUE TITLE
How does this package differ from VoronoiDelaunay.jl?

### ISSUE THREAD

**Issue by juliohm** [matthias-vigelius/DelaunayMeshes.jl#1]
Can you explain your rationale for creating a new package for triangulation?

**Comment by matthias-vigelius** [comment]
* constrained triangulation
* mesh refinement with off-center method (still in development)

**Comment by juliohm** [comment]
Should this package be named ConstrainedDelaunay.jl instead? The name doesn't highlight the difference. I thought it implemented the same method and most people will also think it is the case. Just giving you a hint if you want to get more users and more feedback.

**Comment by matthias-vigelius** [comment]
The focus of this package is to provide the means to obtain high-quality
meshes for solvers. The constrained Delaunay algorithm is only a part of
that so I don't think it should take such a prominent position in the
title. I will extend the documentation to include that point.

Am 22.02.2017 6:35 vorm. schrieb "Júlio Hoffimann" <notifications@github.com
